url: https://matheusfacure.github.io/

# Site settings
title: "{Quinhentos: Nove}"
email: matheusfacure01@gmail.com
description: "Explorando Aprendizado de Máquina nas Ciências Humanas e Sociais"


# Team names, titles and social links
people:
- name: Matheus Facure
  pic: 1
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/matheus-facure-7b0099117
  - title: github
    url: https://github.com/matheusfacure
  - title: facebook 
    url: https://www.facebook.com/matheus.facure.9


# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge